name: ml-heartproj
channels:
- conda-forge
- nodefaults
dependencies:
- python >3.11
- matplotlib >=3.10.6,<4
- numpy >=2.3.3,<3
- imageio >=2.37.0,<3
- scikit-learn >=1.7.2,<2
- notebook >=7.4.5,<8
- pandas >=2.3.2,<3
- scipy >=1.16.1,<2
- statsmodels >=0.14.5,<0.15
- jupyter >=1.1.1,<2
- jupyterlab >=4.4.7,<5
- pip
- pip:
  - kagglehub >=0.3.13